name: latte
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py39hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=2.0.0=py39h4eded50_0
  - charset-normalizer=3.4.4=py39h06a4308_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=6.1.1=hecf7045_5
  - filelock=3.17.0=py39h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py39h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h3539ee5_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.8.0.2=0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.2.1=py39h06a4308_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pillow=11.3.0=py39hb1c3d2d_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_1
  - python=3.9.25=h0dcde21_1
  - pytorch=2.0.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py39h06a4308_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.0.2=py39_cu117
  - torchtriton=2.0.0=py39
  - torchvision=0.15.2=py39_cu117
  - typing_extensions=4.15.0=py39h06a4308_0
  - urllib3=2.5.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fonttools==4.60.2
      - grpcio==1.76.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.5.3
      - kiwisolver==1.4.7
      - markdown==3.9
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - narwhals==2.14.0
      - numpy==1.24.4
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - plotly==6.5.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - tzdata==2025.3
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - zipp==3.23.0
prefix: /home/cheolseok/miniconda3/envs/latte
