default: 
  train_config:
    data_dir: 'Data/'
    epochs: 300
    learning_rate: 0.001
    sche_gamma: 0.98
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    not_use_power_of_two: false
  model_config:
    num_heads: 4
    depth: 4
    hidden_dim: 64
    num_latents: 32
    num_memories: 256
    mlp_ratio: 4.0
    dropout_prob: 0.1
    temperature: 0.1
    sim_type: 'cos'
    top_k: null