default: 
  train_config:
    data_dir: 'Data/'
    epochs: 250
    learning_rate: 0.05
    sche_gamma: 0.98
    patience: 20
    min_delta: 0.0001
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    not_use_power_of_two: false
    latent_ratio: null
    memory_ratio: null
    use_latent_F: false
  model_config:
    num_heads: 4
    num_latents: null
    num_memories: null
    depth: 4
    hidden_dim: 8
    mlp_ratio: 4.0
    dropout_prob: 0.0
    temperature: 1
    sim_type: 'cos'
    shrink_thred: 0
    use_entropy_loss_as_score: null
    top_k: null
   
census:
  batch_size: 2048

fraud:
  batch_size: 2048

nslkdd:
  batch_size: 2048
