default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    not_use_power_of_two: false
  model_config:
    num_heads: 4
    num_latents: null
    num_memories: null
    depth: 4
    hidden_dim: 8
    mlp_ratio: 4.0
    dropout_prob: 0.0
    temperature: 1
    sim_type: 'cos'
    shrink_thred: 0
    use_entropy_loss_as_score: null
    top_k: null


arrhythmia:
  latent_ratio: 1.0
  memory_ratio: 0.5
  top_k: 5
  temperature: 1.0

breastw:
  latent_ratio: 4.0
  memory_ratio: 0.5
  top_k: 1
  temperature: 0.1

cardio:
  latent_ratio: 4.0
  memory_ratio: 1.0
  top_k: 1
  temperature: 0.1

cardiotocography:
  latent_ratio: 2.0
  memory_ratio: 4.0
  top_k: 1
  temperature: 0.1

campaign: 
  latent_ratio: 4.0
  memory_ratio: 1.0
  top_k: 15
  temperature: 0.5

census:
  latent_ratio: 4.0
  memory_ratio: 2.0
  temperature: 0.1
  epochs: 50
  batch_size: 2048

fraud:
  latent_ratio: 1.0
  memory_ratio: 1.0
  temperature: 0.1
  epochs: 50
  batch_size: 2048

glass:
  latent_ratio: 0.5
  memory_ratio: 4.0
  top_k: 5
  temperature: 0.1

ionosphere:
  latent_ratio: 1.0
  memory_ratio: 0.5
  top_k: 5
  temperature: 1.0

mammography: 
  latent_ratio: 2.0
  memory_ratio: 2.0
  top_k: 5
  temperature: 0.5

nslkdd:
  latent_ratio: 1.0
  memory_ratio: 1.0
  temperature: 0.1
  epochs: 50
  batch_size: 2048

optdigits:
  latent_ratio: 0.5
  memory_ratio: 2.0
  top_k: 5
  temperature: 0.1

pendigits: 
  latent_ratio: 4.0
  memory_ratio: 1.0
  top_k: 15
  temperature: 0.1

pima:
  latent_ratio: 2.0
  memory_ratio: 4.0
  top_k: 10
  temperature: 0.1

satellite:
  latent_ratio: 0.5
  memory_ratio: 4.0
  top_k: 5
  temperature: 1.0

"satimage-2": 
  latent_ratio: 1.0
  memory_ratio: 4.0
  top_k: 15
  temperature: 1.0

shuttle: 
  latent_ratio: 1.0
  memory_ratio: 2.0
  top_k: 10
  temperature: 1.0

thyroid:
  latent_ratio: 1.0
  memory_ratio: 1.0
  top_k: 1
  temperature: 0.1

wbc:
  latent_ratio: 4.0
  memory_ratio: 0.5
  top_k: 10
  temperature: 1.0

wine:
  latent_ratio: 2.0
  memory_ratio: 1.0
  top_k: 10
  temperature: 0.5