default: 
  train_config:
    data_dir: 'Data/'
    epochs: 250
    learning_rate: 0.01
    sche_gamma: 0.95
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    patience: 20
    use_amp: false
  model_config:
    hidden_dim: 16
    depth: 4
    num_heads: 4
    mlp_ratio: 4.0
    dropout_prob: 0.0
    use_rope: true
    num_permutations: 30



census:
  batch_size: 256
  learning_rate: 0.001
  sche_gamma: 0.98
  patience: 50
  min_delta: 0.00001
  epochs: 50
  use_amp: true
  use_flash_attn: true

fraud:
  batch_size: 2048
  learning_rate: 0.001
  sche_gamma: 0.98
  patience: 50
  min_delta: 0.00001

nslkdd:
  batch_size: 1024
  learning_rate: 0.001
  sche_gamma: 0.98
  patience: 50
  min_delta: 0.00001
  use_amp: true
  use_flash_attn: true

 