default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
  model_config:
    num_heads: 4
    depth: 2
    hidden_dim: 16
    mlp_ratio: 4.0
    dropout_prob: 0.1
    train_mask_prob: 0.15
    test_mask_prob: 0.15

fraud:
  batch_size: 2048
  epochs: 50

glass:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

wine:
  num_heads: 4
  depth: 2
  hidden_dim: 8
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

breastw :
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

pima:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

thyroid:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.1
  test_mask_prob: 0.15

pendigits: 
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.25
  test_mask_prob: 0.15

mammography:
  num_heads: 4
  depth: 2
  hidden_dim: 8
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.25
  test_mask_prob: 0.15

cardio:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

satimage-2:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.1
  test_mask_prob: 0.1

satellite:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.1
  test_mask_prob: 0.1
