default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    use_mask_bank: false
  model_config:
    num_heads: 4
    depth: 2
    hidden_dim: 16
    mlp_ratio: 4.0
    dropout_prob: 0.1
    train_mask_prob: 0.15
    test_mask_prob: 0.15

census:
  hidden_dim: 8
  batch_size: 128
  learning_rate: 0.001
  use_mask_bank: false
  epochs: 50

nslkdd:
  batch_size: 512
  use_mask_bank: false
  epochs: 50

fraud:
  batch_size: 2048
  use_mask_bank: false
  epochs: 50

glass:
  num_heads: 4
  use_mask_bank: true
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

wine:
  use_mask_bank: true
  num_heads: 4
  depth: 2
  hidden_dim: 8
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

breastw :
  num_heads: 4
  depth: 2
  hidden_dim: 16
  use_mask_bank: true
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15

pima:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15
  use_mask_bank: true

thyroid:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.1
  test_mask_prob: 0.15
  use_mask_bank: true

pendigits: 
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.25
  test_mask_prob: 0.15
  use_mask_bank: true

mammography:
  num_heads: 4
  depth: 2
  hidden_dim: 8
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.25
  test_mask_prob: 0.15
  use_mask_bank: true

cardio:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.15
  test_mask_prob: 0.15
  use_mask_bank: true

satimage-2:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.1
  test_mask_prob: 0.1
  use_mask_bank: true

satellite:
  num_heads: 4
  depth: 2
  hidden_dim: 16
  dropout_prob: 0.1
  learning_rate: 0.01
  train_mask_prob: 0.1
  test_mask_prob: 0.1
  use_mask_bank: true
