default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.01
    sche_gamma: 0.95
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    patience: 20
    min_delta: 0
    use_amp: false
  model_config:
    num_features: null
    hidden_dim: 16
    depth: 4
    depth_enc: null
    depth_dec: null
    num_heads: 4
    mlp_ratio: 4.0
    dropout_prob: 0.0
    use_flash_attn: false

wine:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
  epochs: 100
  batch_size: 32

glass:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
  epochs: 100
  batch_size: 64

wbc:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001

ionosphere:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
  batch_size: 128

arrhythmia:  
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
  epochs: 100

breastw: 
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
  epochs: 100

pima: 
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
  batch_size: 64

optdigits:
  patience: 100
  preprocess: 'none'
  hidden_dim: 64
  learning_rate: 0.001
  epochs: 100

cardio: 
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001
 
cardiotocography: 
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001
 
thyroid:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

satellite:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

satimage-2:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

pendigits:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

mammography:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

campaign:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

shuttle:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

fraud:
  batch_size: 2048
  patience: 20
  hidden_dim: 128
  learning_rate: 0.001

nslkdd:
  batch_size: 2048
  patience: 20
  epochs: 50
  use_amp: true
  use_flash_attn: true
  hidden_dim: 128
  learning_rate: 0.001

census:
  batch_size: 256
  patience: 20
  epochs: 50
  use_amp: true
  use_flash_attn: true
  hidden_dim: 128
  learning_rate: 0.001