default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.01
    sche_gamma: 0.95
    batch_size: 128
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    patience: 10
    min_delta: 0
    use_amp: false
  model_config:
    num_features: null
    hidden_dim: 16
    depth: 4
    depth_enc: null
    depth_dec: null
    num_heads: 4
    mlp_ratio: 4.0
    dropout_prob: 0.0
    temperature: 0.2
    contra_loss_weight: 0.05
    cycle_loss_weight: 0.01
    dacl_alpha: 0.9
    dacl_beta: 0.8
    use_flash_attn: false
    use_bn: false
    use_bn_proj: false
    use_swap: false

wine:
  epochs: 50
  hidden_dim: 64
  learning_rate: 0.01

glass:
  hidden_dim: 64
  learning_rate: 0.01

wbc:
  hidden_dim: 64
  learning_rate: 0.01

ionosphere:
  hidden_dim: 64
  learning_rate: 0.01

arrhythmia:  
  hidden_dim: 64
  learning_rate: 0.01

breastw: 
  hidden_dim: 64
  learning_rate: 0.01

pima: 
  hidden_dim: 64
  learning_rate: 0.01

optdigits:
  patience: 50
  hidden_dim: 64
  learning_rate: 0.01

cardio: 
  patience: 50
  hidden_dim: 128
  learning_rate: 0.001

cardiotocography: 
  patience: 50
  hidden_dim: 128
  learning_rate: 0.001
 
thyroid:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

satellite:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

satimage-2:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

pendigits:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

mammography:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

campaign:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

shuttle:
  patience: 10
  hidden_dim: 128
  learning_rate: 0.001

fraud:
  batch_size: 2048
  patience: 20
  hidden_dim: 128

nslkdd:
  batch_size: 1024
  patience: 20
  epochs: 50
  use_amp: true
  use_flash_attn: true
  hidden_dim: 128
  learning_rate: 0.001

census:
  batch_size: 128
  patience: 20
  epochs: 50
  use_amp: true
  use_flash_attn: true
  hidden_dim: 128
  learning_rate: 0.001