default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.01
    sche_gamma: 0.95
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    patience: 20
    min_delta: 0
    use_amp: false
  model_config:
    num_features: null
    hidden_dim: 16
    depth: 4
    num_heads: 4
    mlp_ratio: 4.0
    dropout_prob: 0.0
    use_flash_attn: false
    mask_ratio: 0.1
    num_eval_repeat: 50
    eval_chunk_size: 50
    share_mask: true

# small-scale
wine:
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

glass:
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

wbc:
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

ionosphere:
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

arrhythmia:  
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01
  eval_chunk_size: 10

breastw: 
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

pima: 
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

optdigits:
  patience: 10
  hidden_dim: 32
  learning_rate: 0.01

# large-scale
cardio: 
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
 
cardiotocography: 
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001
 
thyroid:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001

satellite:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001

satimage-2:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001

pendigits:
  patience: 10
  hidden_dim: 64
  learning_rate: 0.001

mammography:
  patience: 10
  hidden_dim: 64
  eval_chunk_size: 5
  learning_rate: 0.001

campaign:
  patience: 10
  hidden_dim: 64
  eval_chunk_size: 5
  learning_rate: 0.001

shuttle:
  patience: 10
  hidden_dim: 64
  eval_chunk_size: 5
  learning_rate: 0.001

fraud:
  batch_size: 2048
  patience: 20
  hidden_dim: 64
  eval_chunk_size: 5
  learning_rate: 0.001

nslkdd:
  batch_size: 2048
  patience: 20
  epochs: 50
  use_amp: true
  use_flash_attn: true
  eval_chunk_size: 1
  hidden_dim: 64
  learning_rate: 0.001

census:
  batch_size: 512
  patience: 20
  epochs: 50
  use_amp: true
  use_flash_attn: true
  eval_chunk_size: 1
  hidden_dim: 64
  learning_rate: 0.001